### ISSUE TITLE
Conflicting block

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#10]
Starting on line 5346 of fml-client-latest.log

`[15:33:25] [Client thread/WARN] [FML/Railcraft]: A mod has attempted to assign Block mods.railcraft.common.fluids.BlockRailcraftFluidFinite@7ba3bc9b to the Fluid 'steam' but this Fluid has already been linked to the Block cofh.thermalfoundation.fluid.BlockFluidSteam@100a42a0. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.
`

**Comment by Weikardzaena** [comment]
I'll take a look at this one too

**Comment by Weikardzaena** [comment]
Done.  See pull request

**Comment by superzanti** [comment]
Fixed in #28
