### ISSUE TITLE
Add mods

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#14]
There were a couple mods from the last server that we want to add
- warpbook
- headcrumbs
- dynmap
- elementalcaves
- optifine

**Comment by CRezent** [comment]
I will be working on adding these mods.

**Comment by CRezent** [comment]
The above mods were added and pull requests were made. This issue is now closed by CRezent on 4/24/2016

**Comment by superzanti** [comment]
Dynmap is a server-side only mod so we'll have to add it to the server at some point.

All the other mods have been added.

This is fixed as of [this commit.](https://github.com/superzanti/TheVerse/commit/6e32057e9c3c35eed90d8cce3851f807333cf2d7)
