### ISSUE TITLE
Check over all the config files

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#15]
Check all the config files for conflicts and options.

We want to remove all auto-updating and auto-notification features from all the configs (serversync will help us with this).

**Comment by CRezent** [comment]
Done. Pull request submitted. This pull request does not cover the config files that will be added from the ISSUE-NewMods pull. Creating a seperate issue for those config files as this one is closed.

**Comment by superzanti** [comment]
Please re-submit this pull.
