### ISSUE TITLE
Disable Auto Update for new mods

### ISSUE THREAD

**Issue by CRezent** [superzanti/TheVerse#25]
Auto update and auto notification must be disabled for the mods added in the new mods issue. namely all cfg files created by:

warpbook
headcrumbs
dynmap
elementalcaves
optifine

need to be checked

**Comment by superzanti** [comment]
Done in [commit](https://github.com/superzanti/TheVerse/commit/011173b8e7d03d71b3427e98071cd9026d650a7c)
