### ISSUE TITLE
Mac Start

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#26]
I heard people report in the past that the MacStart does not work.

Can someone with a mac verify this and test it?

**Comment by Weikardzaena** [comment]
I'll look into it

**Comment by Weikardzaena** [comment]
I don't think that this version of the Mac_Start.app is actually an app folder.  Finder doesn't see it (even though it can see the .git folder...) and when I try to run it from the terminal it just says "Unable to find application" even though it's there in the directory (I can see it via `ls -la`).  So I think something is just wrong with it and it is probably to our benefit to just redo it.

**Comment by superzanti** [comment]
Could you help re-do it? I don't have access to a mac.

Looking at the linux_start.sh should help you. In fact, I know you can just execute the sh on mac and have it work (I believe). However, I'd rather not guide users through opening a terminal. Lets try to keep some form of double click functionality.

**Comment by Weikardzaena** [comment]
Yeah I agree, a point and click mac start would definitely be the way to go.  I'll do something about it

**Comment by superzanti** [comment]
Thanks. You might want to double check that running the linux_start.sh through the terminal works.

**Comment by Weikardzaena** [comment]
Let it be known that running the Linux_Start.sh on a Mac does *not* work because Macs are dumb and they create their own directory tree to store minecraft local data.  This can be fixed, but as of right now it is unplayable on a Mac unless you move stuff around.

**Comment by superzanti** [comment]
Gotcha. Yeah, I believe that's why I made the mac app originally because I needed to force the mac to use /MY/ minecraft directory instead of trying to make it's own for the local minecraft data.

**Comment by CRezent** [comment]
Is anyone actually playing on a mac?

**Comment by Weikardzaena** [comment]
I will be some times.  I like to be able to pop open my only portable machine that's powerful enough to actually run the client.

**Comment by CRezent** [comment]
ok

**Comment by superzanti** [comment]
Lee, Lindsey, and Jamie are all playing on mac. Lee's been wanting to play for a while itoo but we never actually got him set up on the mac before we quit playing.

**Comment by CRezent** [comment]
This is the last bug to fix before launch as all of the others are fixed or already in the Direwolf 20 pack and there is not currently a fix for them.

**Comment by superzanti** [comment]
I believe this is fixed.
