### ISSUE TITLE
NEIAddons Requirements unmet ExNihilo addon not loading

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#3]
on line 6849 of fml-client-latest.log

`[15:33:34] [Client thread/ERROR] [NEIAddons|ExNihilo/NEIAddons|ExNihilo]: Requirements unmet, Ex Nihilo Addon not loading`

**Comment by CRezent** [comment]
After googling error, it says the problem is most often caused by running out of memory. So maybe increase that on the server side.

**Comment by superzanti** [comment]
This is actually produced by NEIAddons while looking for the mod ExNihilo which we don't have. It looks like this error can be safely ignored but it piqued my curiosity and I had to check out the ExNilio mod.

I might add it.

**Comment by superzanti** [comment]
Fixed by adding the new mod.

If no objections then this issue is closed.
