### ISSUE TITLE
Press 'e' to open inventory not going away

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#30]
Okay is anyone else having this issue? Cause I can't figure it out.

**Comment by CRezent** [comment]
I saw that too

**Comment by CRezent** [comment]
Open .minecraft folder
2. Then look for the name of the file as "options" to open it.
3. Then locate the point "showInventoryAchievementHint: true,"
4. Edit details of the true to false, then save the file to
5. Open game and Enjoy!

**Comment by CRezent** [comment]
maybe that will work. Did not test or push anything

**Comment by superzanti** [comment]
Fixed as of most recent [commit](https://github.com/superzanti/TheVerse/commit/5b56244ba9e35b4d23b9791035a6f560e77cca36).

Thanks CRezent for the tip. Closing.

**Comment by CRezent** [comment]
So it looks like still stays showing on the screen but if you do another achievement at any time then it shows up with that one and all the other achevements go away. So just punch a tree when you get on the server for the first time and the problems will be over.

**Comment by superzanti** [comment]
Are you sure it's still there? Did you do a pull recently? You should have the options file.

**Comment by CRezent** [comment]
I pulled 5 mins ago

**Comment by CRezent** [comment]
Looks like it just happens once per player not per world.
