### ISSUE TITLE
PneumaticCraft ctmlib couldn't be found

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#7]
Line 16545 of fml-client-latest.log

`[15:34:02] [Client thread/ERROR] [PneumaticCraft/PneumaticCraft]: Chisel's ClientUtils inside ctmlib couldn't be found! No support for connected texture blocks for camouflage is given`

**Comment by CRezent** [comment]
Couldn't find a solution. This looks like the link but there doesn't seem to be any fix yet and I tried running it with the most recent versions and it didn't fix it. here is the link to the bug

https://github.com/MineMaarten/PneumaticCraft/issues/766

**Comment by Weikardzaena** [comment]
Same error appears in Direwolf20's FTB modpack launcher, so we can probably ignore this.
